spring:
  data:
    mongodb:
      username: zaulT
      password: myPassword
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090